In [1]:
from sklearn.metrics import log_loss

In [2]:
import numy as np

ModuleNotFoundError: No module named 'numy'

In [3]:
import numpy as np

In [4]:
ytrue = np.random.binomial(1,0.5, 100)

In [5]:
ytrue

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1])

In [6]:
ytrue[:10]

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [7]:
ppred = np.random.random(size=100)

In [8]:
ppred[:10]

array([0.24818336, 0.48265526, 0.33255375, 0.34345694, 0.23160705,
       0.35764411, 0.78077157, 0.02826644, 0.93196058, 0.15495489])

In [9]:
log_loss(ytrue, ppred)

1.1196890636196957

In [10]:
ppred2 = (ytrue + 0.01)*np.random.random(size=100)

In [11]:
ppred2

array([5.67172204e-01, 1.94636861e-03, 2.14277953e-03, 1.06506422e-01,
       3.31575784e-03, 9.13472690e-03, 3.95761186e-03, 7.98926244e-03,
       6.13067823e-01, 2.65910346e-01, 1.86842614e-01, 9.70228232e-03,
       7.58512439e-01, 9.05984068e-01, 4.92389459e-03, 2.12709242e-03,
       5.16962742e-03, 7.04567995e-03, 8.69589543e-03, 9.93002858e-01,
       7.63842017e-03, 2.01131220e-01, 2.63530258e-03, 1.90599585e-03,
       2.28331779e-01, 7.32405613e-03, 4.80299192e-03, 7.21874565e-03,
       4.27462636e-03, 5.58054906e-03, 8.20528192e-01, 1.78926127e-03,
       1.34396212e-03, 8.10791670e-03, 7.18244866e-03, 9.48122273e-01,
       1.65451599e-01, 6.93464574e-01, 1.14189484e-01, 6.81880583e-03,
       3.61592875e-03, 2.91657167e-01, 9.54663313e-03, 3.08805399e-01,
       6.59389558e-01, 7.13553374e-01, 2.68526747e-03, 2.93998092e-03,
       2.05870199e-01, 1.22010954e-03, 7.43707594e-01, 7.65384741e-01,
       6.08449648e-03, 2.61695471e-03, 7.55194879e-03, 7.42590128e-01,
      

In [12]:
ppred2.round(3)

array([0.567, 0.002, 0.002, 0.107, 0.003, 0.009, 0.004, 0.008, 0.613,
       0.266, 0.187, 0.01 , 0.759, 0.906, 0.005, 0.002, 0.005, 0.007,
       0.009, 0.993, 0.008, 0.201, 0.003, 0.002, 0.228, 0.007, 0.005,
       0.007, 0.004, 0.006, 0.821, 0.002, 0.001, 0.008, 0.007, 0.948,
       0.165, 0.693, 0.114, 0.007, 0.004, 0.292, 0.01 , 0.309, 0.659,
       0.714, 0.003, 0.003, 0.206, 0.001, 0.744, 0.765, 0.006, 0.003,
       0.008, 0.743, 0.345, 0.003, 0.861, 0.009, 0.26 , 0.003, 0.01 ,
       0.403, 0.005, 0.318, 0.344, 0.776, 0.   , 0.371, 0.088, 0.936,
       0.004, 0.432, 0.005, 0.002, 0.208, 0.807, 0.267, 0.004, 0.008,
       0.891, 0.727, 0.927, 0.672, 0.566, 0.406, 0.004, 0.371, 0.337,
       0.351, 0.007, 0.938, 0.134, 0.803, 0.001, 0.309, 0.414, 0.007,
       0.488])

In [13]:
ppred2.max()

0.993002857944016

In [14]:
 ytrue[:10]

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 1])

In [15]:
ppred2[:10].round(3)

array([0.567, 0.002, 0.002, 0.107, 0.003, 0.009, 0.004, 0.008, 0.613,
       0.266])

In [16]:
ppred3 = ytrue +0.1

In [17]:
ppred3[:10]

array([1.1, 0.1, 0.1, 1.1, 0.1, 0.1, 0.1, 0.1, 1.1, 1.1])

In [18]:
log_loss(ytrue, ppred3)

0.04951944235917888