In [93]:
from sklearn.model_selection import cross_val_score
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_moons
from sklearn.linear_model import LogisticRegression
from sklearn import datasets, linear_model
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import seaborn as sns
import sklearn.metrics as skm

In [94]:
df = pd.read_csv('pumps.csv',\
                 index_col=0)

In [95]:
df2 = pd.read_csv('pumps_y.csv',\
                 index_col=0)

In [96]:
df3 = df2.join(df)

In [97]:
df3 = df3[df3.longitude !=0]

In [98]:
df3 = df3[df3.construction_year > 1000]

In [99]:
df3 = df3[df3.construction_year > 100]

In [101]:
df3.shape

(38691, 40)

In [102]:
X=df3[['construction_year']].to_numpy()

In [83]:
#z=df3[['region']].to_numpy()

In [84]:
#z = pd.factorize(z[:,0])

In [103]:
X2 = list(X)

In [104]:
y=df3[['population']].to_numpy()

In [87]:
#y,labels = pd.factorize(y[:,0])

In [105]:
y

array([[109],
       [280],
       [250],
       ...,
       [125],
       [ 56],
       [150]], dtype=int64)

In [106]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.25, random_state=42)

m = LogisticRegression(solver='lbfgs')
#m = LogisticRegression(solver='lbfgs')
m.fit(Xtrain, ytrain)
m.score(Xtrain, ytrain)

C:\Users\casti\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\casti\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


0.17837204493762493

In [110]:
ypred = m.predict(Xtest)
ypred
#np.unique(ypred)
#ypred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [111]:
cm = confusion_matrix(ytest, ypred )
cm

array([[   0,  318,    0, ...,    0,    0,    0],
       [   0, 1745,    0, ...,    0,    0,    0],
       [   0,    4,    0, ...,    0,    0,    0],
       ...,
       [   0,    1,    0, ...,    0,    0,    0],
       [   0,    1,    0, ...,    0,    0,    0],
       [   0,    1,    0, ...,    0,    0,    0]], dtype=int64)

In [112]:
m.score(Xtest, ytest)
ypred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [113]:
Xtest[:3]
m.predict(Xtest[:3])
ypred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [115]:
#ugur=1.2345675
#round(ugur,2)
m.predict_proba(Xtest[:3].round(3))
#m.predict_proba(Xtest[:3].round(3))

array([[3.72266345e-02, 1.82598756e-01, 1.54915086e-04, ...,
        1.17103334e-04, 3.96481389e-05, 3.91990124e-05],
       [3.77601629e-02, 1.92142743e-01, 1.40966958e-04, ...,
        1.05986000e-04, 3.51425217e-05, 3.47368024e-05],
       [3.75830785e-02, 1.88854208e-01, 1.45613570e-04, ...,
        1.09681910e-04, 3.66287358e-05, 3.62085791e-05]])

In [118]:
ytest

array([[   1],
       [1250],
       [ 600],
       ...,
       [ 300],
       [  15],
       [1200]], dtype=int64)

In [119]:
#df4 = linear_model.Lasso()
#df4 = df3.SVC(kernel='linear', C=1.0, probability=True)
x = cross_val_score(m, X, y, cv=20)
#print(cross_val_score(df4, X, y, cv=20))
#print(x)
ytest.shape

C:\Users\casti\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_split.py:657: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=20.
  % (min_groups, self.n_splits)), Warning)
C:\Users\casti\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\casti\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)
C:\Users\casti\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y wa

KeyboardInterrupt: 

In [ ]:
m
#ypred

In [62]:
m.score(Xtrain, ytrain)
ypred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [64]:
m.score(Xtest, ytest)
ypred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [66]:
m.score(X,y)
ypred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [68]:
m = LogisticRegression(solver='lbfgs')
m.fit(X, y)
m.score(X, y)
ypred

C:\Users\casti\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [75]:
#from sklearn.metrics import log_loss
#log_loss(ytest, ypred)
#pd.Series(ytest).unique()
#pd.Series(ypred).unique()
ypred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)